language: java

services:
- docker
-
install: true

jobs:
  include:
  - stage: test
    name: Build on OpenJDK 8
    script: ./gradlew --no-daemon build
    jdk: openjdk8
  - name: Build on OpenJDK 11
    script: ./gradlew --no-daemon build
    jdk: openjdk11
  - stage: deploy
    name: Deploy snapshots to Sonatype OSS
    script: bash .travis.deploy.artifacts.sh
    jdk: openjdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
